import type { ReactionCounts } from "@/lib/pageants/types";

export type MissWorldPiece = {
  kicker: string;
  title: string;
  dek: string;
  byline: string;
  image?: string;
  href?: string;
  reactions?: ReactionCounts;
};

export type MissWorldLayout = "cards" | "essay" | "news" | "roll" | "portraits" | "results" | "videos";

export type MissWorldTab = {
  id: string;
  label: string;
  dek: string;
  body: string[];
  pieces: MissWorldPiece[];
  layout?: MissWorldLayout;
};

export const MISS_WORLD_TABS: MissWorldTab[] = [
  {
    id: "info",
    label: "Miss World : Info",
    dek: "The oldest of the Big Four, established in 1951. Beauty with a Purpose.",
    layout: "essay",
    body: [
      "The Miss World originally started as the Festival Bikini Contest, but an embarrassed British media decided to call it with a more modest name, ‘Miss World’. The pageant was met with a lot of criticism in the beginning, so much so that the swim suit was replaced with more modest swim suits after the first contest. The first Miss World (originally Festival Bikini Contest) was Kerstin \"Kiki\" Håkansson from Stockholm, Sweden. She was the first and last winner to be crowned while wearing a bikini.",
      "The Miss World was first aired in 1959 by BBC and gained popularity thereafter and has grown manifolds. In the year 1980, the pageant adopted the slogan ‘Beauty With a Purpose’ and added tests of intelligence and personality in order to avoid criticism of objectifying women. The Miss World has seen its share of controversies; in the year 1970, feminist protestors disrupted the pageant by throwing flour bombs on the ongoing live pageant. In 1976 the pageant included both a Caucasian and African representative for South Africa which lead to a huge furor and many participating countries decided to boycott the pageant.",
      "Miss World pageant has grown manifolds since then; to enter Miss World, the contestant should be the winner of the national title in their respective home nation. Those chosen to represent their nation then compete in the Miss World Finals. Miss World is no longer just a beauty pageant, it has emerged as a platform for young women from across the globe to showcase their talent, intelligence and work towards a greater good. Miss World pageant provides these contestants to display their culture and raise awareness towards various humanitarian causes as every year the pageant raises millions of pounds for charitable work under the banner of ‘Beauty with a Purpose’ program.",
      "The annual final is typically a month long event, with several preliminary galas, dinners, balls and activities, culminating in a globally telecast final show in which the field is narrowed to between 15–20 delegates. Since 2011, winners and finalists of various group and talent events are awarded bonus points to their preliminary scores. Delegates with the highest points (bonus of challenge events included) are qualified to the final round.",
      "Venezuela and India have dominated the Miss World pageant with six titles so far, followed by United Kingdom and Jamaica with five and four wins respectively."
],
    pieces: [
    {
      kicker: "Info",
      title: "Miss World",
      dek: "The Miss World is one of the oldest beauty pageants amongst the Big 4 (four) international beauty pageants. Established in the year 1951, the idea of Miss World beauty pageant was conceptualized by late Eric Morley as the first edition of the Miss World beauty pageant was held in United Kingdom. Miss World is one of the most publicized beauty pageants alongside Miss Universe and Miss Earth pageants.",
      byline: "Established 1951 · United Kingdom",
      image: "/images/instagram/mw-joheirry.jpg",
    },
    {
      kicker: "2020",
      title: "Miss World 2020",
      dek: "There was no pageant held due to covid-19 pandemic.",
      byline: "Angelopedia",
    },
    {
      kicker: "2019",
      title: "Miss World 2019",
      dek: "Toni-Ann Singh from Jamaica was crowned Miss World 2019 at Excel London, United Kingdom on 14th December 2019. She succeeded and was crowned by Miss World 2018 Vanessa Ponce of Mexico. Toni’s court included Ophély Mézino of France and Suman Rao of India who were adjudged first and second runners-up respectively. Here are the Continental Queens of Beauty - Miss World Africa 2019 was Nyekachi Douglas of Nigeria, Miss World Americas 2019 was Elís Miele Coelho of Brazil, Miss World Asia 2019 – Suman Ratan Singh Rao of India, Miss World Caribbean 2019 was Tya Janè Ramey of Trinidad and Tobago, Miss World Europe 2019 was Ophély Mézino of France and Miss World Oceania 2019 was Tajiya Eikura Sahay of Cook Islands.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2019.jpg",
    },
    {
      kicker: "2018",
      title: "Miss World 2018",
      dek: "Vanessa Ponce from Mexico was crowned Miss World 2018 at the Sanya City Arena, China on 8th December 2018 becoming the first woman from her country to win the coveted crown. Vanessa succeeded and was crowned by Miss World 2017 Manushi Chhilar. Nicolene Pichapa Limsnukan of Thailand was adjudged as the runner-up. The Continental Queens of Beauty included – Miss World Africa 2018 was Quiin Abenakyo of Uganda, Miss World America 2018 was Solaris Barba of Panama, Miss World Asia 2018 was Nicolene Limsnukan of Thailand, Miss World Caribbean 2018 was Kadijah Robinson of Jamaica, Miss World Europe 2018 was Maria Vasilevich of Belarus and Miss World Oceania 2018 was Jessica Tyson of New Zealand.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2018.jpg",
    },
    {
      kicker: "2017",
      title: "Miss World 2017",
      dek: "Manushi Chhillar from India was crowned Miss World 2017 at the Sanya City Arena, China on 18th November 2017. 118 contestants from all over the world competed for the international crown. Manushi succeeded and was crowned by Miss World 2016 Stephanie Del Valle from Puerto Rico. She is the sixth Indian woman to win Miss World after Priyanka Chopra won in 2000. Andrea Meza from Mexico and Stephanie Hill from England were adjudged first and second runners-up respectively. The Continental Queens of Beauty included – Miss World Africa 2017 was Magline Jeruto of Kenya, Miss World Americas 2017 was Andrea Meza of Mexico, Miss World Asia 2017 was Achintya Holte Nilsen of Indonesia, Miss World Caribbean 2017 was Solange Sinclair of Jamaica, Miss World Europe 2017 was Stephanie Hill of England and Miss World Oceania 2017 was Annie Evans of New Zealand.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2017.jpg",
    },
    {
      kicker: "2016",
      title: "Miss World 2016",
      dek: "Stephanie Del Valle from Puerto Rico was crowned Miss World 2016 at MGM National Harbor, United States on 18th December 2016. 117 contestants from all over the world competed for the crown. Mireia Lalaguna of Spain crowned her successor at the end of the event finale. It was the second time where Puerto Rico won Miss World, after Wilnelia Merced in 1975. Yaritza Reyes of Dominican Republic and Natasha Mannuela Halim of Indonesia were adjudged first and second runners-up respectively. The Continental Queens of Beauty included – Miss World Africa 2016 was Evelyn Njambi of Kenya, Miss World Americas 2016 was Audra Mari of United States, Miss World Asia 2016 was Natasha Mannuela Halim of Indonesia, Miss World Caribbean 2016 was Yaritza Reyes of Dominican Republic, Miss World Europe 2016 was Lenty Frans of Belgium and Miss World Oceania 2016 was Madeline Cowe of Australia.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2016.jpg",
    },
    {
      kicker: "2015",
      title: "Miss World 2015",
      dek: "Mireia Lalaguna from Spain was crowned the Miss World 2015 at Crown of Beauty Theatre, China on 19th December 2015. 114 contestants from all over the world competed for the crown. Rolene Strauss of South Africa crowned her successor at the end of the event finale. Spain won the Miss World crown for the first time. Sofia Nikitchuk of Russia and Maria Harfantii of Indonesia was adjudged first and second runners-up respectively. The Continental Queens of Beauty included – Miss World Africa 2015 was Liesl Laurie of South Africa, Miss World Americas 2015 was Catharina Choi Nunes of Brazil, Miss World Asia 2015 was Maria Harfanti of Indonesia, Miss World Caribbean 2015 was Sanneta Myrie of Jamaica, Miss World Europe 2015 was Sofia Nikitchuk of Russia, Miss World Oceania 2015 was Tess Alexander of Australia.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2015.jpg",
    },
    {
      kicker: "2014",
      title: "Miss World 2014",
      dek: "Rolene Strauss from South Africa was crowned the Miss World 2014 at ExCeL London, United Kingdom on 14th December 2014. 121 contestants competed for the crown as Megan Young of the Philippines crowned her successor at the end of the event finale. Edina Kulcsár of Hungary and Elizabeth Safrit of United States were adjudged first and second runners-up respectively. The Continental Queens of Beauty consisted of Idah Nguma of Kenya who was Miss World Africa 2014, Elizabeth Safrit of United States who was crowned Miss World Americas 2014, Koyal Rana of India who was adjudged Miss World Asia 2014, Rafieya Husain who was adjudged Miss World Caribbean 2014, Edina Kulcsár of Hungary who was adjudged Miss World Europe 2014 and Courtney Thorpe of Australia who was adjudged Miss World Oceania 2014.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2014.jpg",
    },
    {
      kicker: "2013",
      title: "Miss World 2013",
      dek: "Megan Young from Philippines created history by winning the first ever title for her country as she was crowned Miss World 2013 at the Bali Nusa Dua Convention Center, Indonesia on 28th September 2013. Contestants from 127 countries and territories competed in this year's Miss World pageant, marking the biggest turnout for any major international beauty pageant as of 2021. Marine Lorphelin from France and Carranzar Naa Okailey Shooter from Ghana were adjudged first and second runners-up respectively. The Continental Queens of Beauty included Carranzar Naa Okailey Shooter of Ghana who was adjudged Miss World Africa 2013, Sancler Frantz of Brazil who was adjudged Miss World Americas 2013, Megan Young of Philippines who was adjudged Miss World Asia 2013, Gina Hargitay of Jamaica who was adjudged Miss World Caribbean 2013, Marine Lorphelin of France who was adjudged Miss World Europe 2013 and Erin Holland of Australia who was adjudged Miss World Oceania 2013.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2013.jpg",
    },
    {
      kicker: "2012",
      title: "Miss World 2012",
      dek: "Yu Wenxia from China was crowned Miss World 2012 at the finale held at Dongsheng Fitness Center Stadium, China on 18th August 2012. 116 contestants from all over the world competed for the crown as Ivian Sarcos of Venezuela crowned her successor at the end of the event finale. Sophie Moulds of Wales and Jessica Kahawaty of Australia were adjudged first and second runners-up respectively. The Continental Queens of Beauty included Atong Demach of South Sudan was adjudged Miss World Africa 2012, Mariana Notarangelo of Brazil was adjudged Miss World Americas 2012, Yu Wenxia of China was adjudged Miss World Asia 2012, Deanna Robins of Jamaica was adjudged Miss World Caribbean 2012, Sophie Moulds of Wales who was adjudged Miss World Europe 2012, Jessica Kahawaty of Australia who was adjudged Miss World Oceania 2012.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2012.jpg",
    },
    {
      kicker: "2011",
      title: "Miss World 2011",
      dek: "Ivian Sarcos from Venezuela was crowned Miss World 2011 at the finale held at Earls Court Exhibition Centre, United Kingdom on 6th November 2011. 113 contestants competed for Miss World crown as Alexandria Mills of the United States crowned her successor at the end of the event finale. Gwendoline Ruais of Philippines and Amanda Vilanova of Puerto Rico were adjudged first and second runners-up respectively. The Continental Queens of Beauty included Bokang Montjane of South Africa who was adjudged Miss World Africa 2011, Ivian Sarcos of Venezuela who was adjudged Miss World Americas 2011, Gwendoline Ruais of Philippines who was adjudged Miss World Asia and Oceania 2011, Amanda Vilanova of Puerto Rico who was adjudged Miss World Caribbean 2011 and Alize Lily Mounter of England who was adjudged Miss World Europe 2011.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2011.jpg",
    },
    {
      kicker: "2010",
      title: "Miss World 2010",
      dek: "Alexandria Mills from USA was crowned Miss World 2010 at the finale held at Crown of Beauty Theatre, China on 30th October 2010. 121 contestants from all over the world competed for the crown as Kaiane Aldorino of Gibraltar crowned her successor at the end of the event finale. Emma Wareus of Botswana and Adriana Vasini of Venezuela were adjudged first and second runners-up respectively. The Continental Queens of Beauty included Emma Wareus of Botswana who was adjudged Miss World Africa 2010, Alexandria Mills of United States who was adjudged Miss World Americas 2010, Tang Xiao of China who was adjudged Miss Asia and Pacific 2010, Aiasha Gustave of St. Lucia who was adjudged Miss World Caribbean 2010 and Emma Britt Waldron of Ireland who was adjudged Miss World Europe 2010.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2010.jpg",
    },
    {
      kicker: "2009",
      title: "Miss World 2009",
      dek: "Miss World 2009, the 59th edition of the Miss World, was held on 12th December 2009 at the Gallagher Convention Centre in Johannesburg, South Africa. 112 contestants from all over the world competed for the crown where Ksenia Sukhinova of Russia crowned her successor Kaiane Aldorino of Gibraltar at the end of event finale. Gibraltar pioneered their win at Miss World this year. Tatum Keshwar of South Africa and Perla Beltrán of Mexico were adjudged first and second runners-up respectively. The Continental Queens of Beauty were – Miss World Africa 2009 was Tatum Keshwar of South Africa, Miss World Americas 2009 was Perla Beltrán of Mexico, Miss World Asia and Oceania 2009 was Kim Joo-ri of Korea, Miss World Caribbean 2009 was Ingrid Littré of Martinique and Miss World Europe 2009 was Kaiane Aldorino of Gibraltar.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2009.jpg",
    },
    {
      kicker: "2008",
      title: "Miss World 2008",
      dek: "Miss World 2008, the 58th edition of the Miss World, was held on 13th December 2008 at the Sandton Convention Centre in Johannesburg, South Africa. 109 contestants from all over the world competed for the crown where Zhang Zilin of China crowned Ksenia Sukhinova of Russia as the new Miss World. Parvathy Omanakuttan of India and Gabrielle Walcott of Trinidad and Tobago were adjudged first and second runners-up respectively. Here are the Continental Queens of Beauty – Miss World Africa 2008 was Brigith dos Santos of Angola, Miss World Americas 2008 was Hannelly Quintero of Venezuela, Miss World Asia 2008 was Parvathy Omanakuttan of India, Miss World Caribbean 2008 was Gabrielle Walcott of Trinidad and Tobago and Miss World Europe 2008 was Patricia Yurena Rodríguez of Spain.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2008.jpg",
    },
    {
      kicker: "2007",
      title: "Miss World 2007",
      dek: "Miss World 2007, the 57th edition of the Miss World, was held on 1st December 2007 at the Crown of Beauty Theatre in Sanya, China. Zhang Zilin of China won the Miss World crown and succeeded Tatána Kucharová of the Czech Republic. Micaela Reis of Angola and Carolina Morán of Mexico were adjudged first and second runners-up respectively. Here are the Continental Queens of Beauty – Miss World Africa 2007 was Micaela Reis of Angola, Miss World Americas 2007 was Carolina Moran of Mexico, Miss World Asia and Oceania 2007 was Zhang Zilin of People’s Republic of China, Miss World Caribbean 2007 was Valene Maharaj of Trinidad and Tobago and Miss World Europe 2007 was Annie Oliv of Sweden.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2007.jpg",
    },
    {
      kicker: "2006",
      title: "Miss World 2006",
      dek: "Miss World 2006, the 56th edition of the Miss World, was held on 30th September 2006 at the Sala Kongresowa in Warsaw, Poland. At the end of the event finale, Tatána Kucharová from the Czech Republic was crowned Miss World 2006 by outgoing titleholder Unnur Birna Vilhjálmsdóttir of Iceland. It was the first time ever that the pageant was held in the Continental Europe and a European city other than London, United Kingdom. Ioana Boitor of Romania and Sabrina Houssami of Australia were adjudged first and second runners-up respectively. Here are the Continental Queens of Beauty – Miss World Africa 2006 was Stiviandra Oliveira of Angola, Miss World Americas 2006 was Jane Borges of Brazil, Miss World Asia Pacific 2006 was Sabrina Houssami of Australia, Miss World Caribbean 2006 was Sara Lawrence of Jamaica, Miss World Northern Europe 2006 was Tatána Kucharová of Czech Republic and Miss World Southern Europe 2006 was Ioana Boitor of Romania.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2006.jpg",
    },
    {
      kicker: "2005",
      title: "Miss World 2005",
      dek: "Miss World 2005, the 55th edition of the Miss World, was held on 10th December 2005 at the Crown of Beauty Theatre in Sanya, China. María Julia Mantilla of Peru crowned her successor Unnur Birna Vilhjálmsdóttir of Iceland as the new Miss World. Dafne Molina of Mexico and Ingrid Marie Rivera of Puerto Rico were adjudged first and second runners-up respectively. Here are the Continental Queens of Beauty – Miss World Africa 2005 was Nancy Sumari of Tanzania, Miss World Americas 2005 was Dafne Molina of Mexico, Miss World Asia Pacific 2005 was Oh Eun-young of Korea, Miss World Caribbean 2005 was Ingrid Marie Rivera of Puerto Rico, Miss World Northern Europe 2005 was Unnur Birna Vilhjálmsdóttir of Iceland and Miss World Southern Europe 2005 was Sofia Bruscoli of Italy.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2005.jpg",
    },
    {
      kicker: "2004",
      title: "Miss World 2004",
      dek: "Miss World 2004, the 54th edition of the Miss World, was held on 4th December 2004 at the Crown of Beauty Theatre in Sanya, China where Rosanna Davison of Ireland crowned her successor María Julia Mantilla of Peru as the new Miss World. Claudia Cruz of Dominican Republic and Nancy Randall of United States were adjudged first and second runners-up respectively. Here are the Continental Queens of Beauty – Miss World Africa 2004 was Anita Uwagbale of Nigeria, Miss World Americas 2004 was María Julia Mantilla of Peru, Miss World Asia and Oceania 2004 was Maria Karla Bautista of Philippines, Miss World Caribbean 2004 was Claudia Cruz of Dominican Republic and Miss World Europe 2004 was Katarzyna Borowicz of Poland.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2004.jpg",
    },
    {
      kicker: "2003",
      title: "Miss World 2003",
      dek: "Miss World 2003, the 53rd edition of the Miss World, was held on 6th December 2003 at the Crown of Beauty Theatre in Sanya, China. Azra Akin of Turkey crowned her successor Rosanna Davison of Ireland at the end of the event finale. Rosanna is the daughter of popular musician Chris de Burgh as she claimed Ireland's first major beauty pageant title. Nazanin Afshin-Jam of Canada and Guan Qi of China were adjudged first and second runners-up respectively. Here are the Continental Queens of Beauty – Miss World Africa 2003 was Hayat Ahmed of Ethiopia, Miss World Americas 2003 was Nazanin Afshin-Jam of Canada, Miss World Oceania and Asia 2003 was Guan Qi of China, Miss World Caribbean 2003 was Jade Fulford of Jamaica and Miss World Europe 2003 was Rosanna Davison of Ireland.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2003.jpg",
    },
    {
      kicker: "2002",
      title: "Miss World 2002",
      dek: "Miss World 2002, the 52nd edition of the Miss World, was held on 7th December 2002 at the Alexandra Palace in London, United Kingdom. It was initially intended to be staged in Abuja, but due to religious riots, the pageant was relocated to London. At the end of the event finale, Azra Akin from Turkey won the crown becoming the first ever representative from her country to be crowned Miss World. Natalia Peralta of Colombia and Marina Mora of Peru were adjudged first and second runners-up respectively. It was the first time that audience participation through text messaging together with the scores of the judges helped in determining the results for the Top 20. Here are the Continental Queens of Beauty – Miss World Africa 2002 was Chinenye Akinlade of Nigeria, Miss World Americas 2002 was Natalia Peralta of Colombia, Miss World Asia and Oceania 2002 was Wu Ying Na of China, Miss World Caribbean 2002 was Rachelle Oduber of Aruba and Miss World Europe 2002 was Azra Akin of Turkey.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2002.jpg",
    },
    {
      kicker: "2001",
      title: "Miss World 2001",
      dek: "Miss World 2001, the 51st edition of the Miss World pageant, was held on 16 November 2001 at the Super Bowl of Sun City Entertainment Centre in Sun City, South Africa. Priyanka Chopra of India crowned her successor Agbani Darego of Nigeria at the end of the event as Nigeria pioneered its win at Miss World. Zizi Lee of Aruba and Juliet-Jane Horne of Scotland were adjudged first and second runners-up respectively. Here are the Continental Queens of Beauty – Miss World Africa 2001 was Agbani Darego of Nigeria, Miss World Americas 2001 was Ligia Cristina Argüello of Nicaragua, Miss World Asia and Oceania 2001 was Bing Li of China, Miss World Caribbean 2001 was Zizi Lee of Aruba and Miss World Europe 2001 was Juliet-Jane Horne of Scotland.",
      byline: "Angelopedia",
      image: "/images/miss-world/titleholder-2001.jpg",
    },
    ],
  },
  {
    id: "news",
    label: "Miss World : News",
    dek: "Miss World from the Angelopedia desk.",
    layout: "news",
    body: [],
    pieces: [
    {
      kicker: "News",
      title: "Anudi Gunasekara crowned Miss World Sri Lanka 2024",
      dek: "Anudi Gunasekara has been crowned Miss World Sri Lanka 2024, marking a significant milestone in the country's pageantry. Her win not only highlights her grace and poise but also her dedication to social causes and community service.",
      byline: "By Irina Silva · 30 July 2024",
      image: "/images/miss-world/news/news-sri-lanka.jpg",
      href: "/news/anudi-gunasekara-miss-world-sri-lanka",
    },
    {
      kicker: "News",
      title: "Celebrating a Milestone: Happy 73rd Anniversary, Miss World!",
      dek: "On July 29, 1951, Eric Morley launched Miss World, an international beauty contest that quickly became iconic, with Sweden’s Kiki Hakansson winning the inaugural title. Celebrating 73 years, the pageant has evolved to champion societal contributions through its \"Beauty With a Purpose\" initiative.",
      byline: "By Aakanksha Chugh · 30 July 2024",
      image: "/images/miss-world/news/news-anniversary.jpg",
    },
    {
      kicker: "News",
      title: "Maria Amélia Baptista crowned Miss World Portugal 2024",
      dek: "Maria Amélia Baptista has been crowned Miss World Portugal 2024, impressing with her beauty and winning the Beauty With a Purpose challenge. The 26-year-old, born in Brazil and residing in Porto, will represent Portugal at the 72nd Miss World Festival.",
      byline: "By Camilla Saurez · 29 July 2024",
      image: "/images/miss-world/news/news-portugal.jpg",
    },
    {
      kicker: "News",
      title: "Ariet Sanjarova crowned Miss World Kyrgyzstan 2024",
      dek: "Ariet Sanjarova, a vibrant 21-year-old from Osh, has been named Miss World Kyrgyzstan 2024. She will represent her nation at the 72nd Miss World pageant in 2025. Learn about her inspiring journey and what lies ahead for this emerging star.",
      byline: "By Irina Silva · 26 July 2024",
      image: "/images/miss-world/news/news-kyrgyzstan.jpg",
    },
    {
      kicker: "News",
      title: "Paula Pérez - From Miss World to Miss Universe!",
      dek: "General doctor and former Miss World Spain Paula Pérez is set to represent Comunidad Valenciana at Miss Universe Spain 2024. With a background in healthcare and social causes, her journey to the crown is one to watch.",
      byline: "By Camilla Saurez · 25 July 2024",
      image: "/images/miss-world/news/news-paula-perez.jpg",
    },
    {
      kicker: "News",
      title: "Miss World Champions Beach Cleanup in Sabah",
      dek: "During her visit to Sabah, Krystyna Pyszková, reigning Miss World, joined a beach cleanup at Pantai Dalit Beach. The initiative, led by Miss World CEO Julia Morley and local officials, aimed to preserve Sabah's pristine environment.",
      byline: "By Irina Silva · 24 July 2024",
      image: "/images/miss-world/news/news-sabah.jpg",
    },
    {
      kicker: "News",
      title: "Mihaela Nicolaev crowned Miss Moldova 2024",
      dek: "Dubasari's own Mihaela Nicolaev, at 19 years old, has clinched the prestigious title of Miss Moldova 2024, marking a significant milestone in her promising career in the world of beauty and grace. Hailing from the heart of Moldova, Michelle's journey to the crown has captured the hearts of many.",
      byline: "By Angelique Reyes · 19 July 2024",
      image: "/images/miss-world/news/news-moldova.jpg",
    },
    {
      kicker: "News",
      title: "Krishnah Gravidez crowned Miss World Philippines 2024",
      dek: "Krishnah Marie Gravidez crowned Miss World Philippines 2024 at the Mall of Asia Arena on July 19, 2024. Known for her previous titles, including Miss Universe Philippines 2023 and Miss Charm Philippines 2024, Gravidez dazzled the audience.",
      byline: "By Irina Silva · 19 July 2024",
      image: "/images/miss-world/news/news-philippines.jpg",
      href: "/news/krishnah-gravidez",
    },
    {
      kicker: "News",
      title: "Julia Morley and Krystyna Pyszkova's Glamorous Entry at Miss World Philippines 2024",
      dek: "Mrs. Julia Morley, Chairman and CEO of the Miss World Organization, and Krystyna Pyszkova, Miss World 2024, will arrive in the Philippines on July 16, 2024. Their visit promises a celebration of beauty, culture, and global unity as they participate in the Miss World Philippines 2024 pageant.",
      byline: "By Camilla Saurez · 15 July 2024",
      image: "/images/miss-world/news/news-julia-morley.jpg",
    },
    {
      kicker: "News",
      title: "Mame Fama Gaye crowned Miss Senegal 2024",
      dek: "Mame Fama Gaye, a 24-year-old with a Master's degree in Criminal Science, has been crowned Miss Senegal 2024. Representing Fatick, Gaye's win is a testament to her beauty, intelligence, and dedication to social causes, setting a new standard for future pageant queens.",
      byline: "By Angelique Reyes · 13 July 2024",
      image: "/images/miss-world/news/news-senegal.jpg",
    },
    {
      kicker: "News",
      title: "Jessia Islam appointed for Miss Grand Bangladesh 2024",
      dek: "Jessia Islam, the 25-year-old Dhaka-born beauty queen, has been appointed Miss Grand Bangladesh 2024. With a rich pageant history including Miss World Bangladesh 2017 and Miss Charm Bangladesh 2023, Jessia continues to shine on the international stage.",
      byline: "By Aakanksha Chugh · 08 July 2024",
      image: "/images/miss-world/news/news-jessia.jpg",
    },
    {
      kicker: "News",
      title: "Olga Chavez crowned Miss World Bolivia 2024",
      dek: "Olga Chavez, a beacon of grace and intelligence, has been crowned Miss World Bolivia 2024. At the age of 24, this remarkable woman from Santa Cruz is set to represent Bolivia on the global stage, showcasing her beauty, intellect, and dedication to social causes.",
      byline: "By Angelique Reyes · 01 July 2024",
      image: "/images/miss-world/news/news-bolivia.jpg",
    },
    {
      kicker: "News",
      title: "Marie-Emmanuelle Diamala crowned Miss Côte d’Ivoire 2024",
      dek: "Marie-Emmanuelle Diamala, a 20-year-old student from Sud-Comoé, has been crowned Miss Côte d'Ivoire 2024, impressing judges with her dedication to environmental conservation and community development. Her victory in Abidjan highlights her as a role model committed to promoting education.",
      byline: "By Camilla Saurez · 01 July 2024",
      image: "/images/miss-world/news/news-cote-divoire.jpg",
    },
    {
      kicker: "News",
      title: "‘I wake up each day with the purpose’: In Conversation with Miss World Ecuador ’24, Sandra Alvarado",
      dek: "‘I wake up each day with the purpose’: In Conversation with Miss World Ecuador ’24, Sandra Alvarado.",
      byline: "By Aakanksha Chugh · 01 July 2024",
      image: "/images/miss-world/news/news-ecuador.jpg",
    },
    {
      kicker: "News",
      title: "Maja Klajda is crowned Miss World Poland 2024",
      dek: "Maja Klajda wins Miss Polonia 2024, securing her spot as Miss World Poland. She'll represent Poland at the 72nd Miss World Festival, with Agata Kwiecień and Emily Reng as runners-up.",
      byline: "By Camilla Saurez · 29 June 2024",
      image: "/images/miss-world/news/news-poland.jpg",
    },
    {
      kicker: "News",
      title: "Anna-Lise Nanton Crowned Miss World Trinidad & Tobago 2024",
      dek: "Anna-Lise Nanton, a 26-year-old geotechnical engineer and advocate for women's empowerment, will represent Trinidad & Tobago at the 72nd Miss World Festival.",
      byline: "By Angelique Reyes · 24 June 2024",
      image: "/images/miss-world/news/news-trinidad.jpg",
    },
    {
      kicker: "News",
      title: "Andrea Katzenbach crowned Miss World Hungary 2024",
      dek: "Andrea Katzenbach, a 23-year-old economist and graphic/web designer from Kiskőrös, has been crowned Miss World Hungary 2024. She is set to represent Hungary at the prestigious 72nd Miss World Festival, showcasing her intellect and creativity alongside her beauty.",
      byline: "By Camilla Saurez · 24 June 2024",
      image: "/images/miss-world/news/news-hungary.jpg",
    },
    {
      kicker: "News",
      title: "Aleksandra Rutović crowned Miss Serbia 2024",
      dek: "Aleksandra Rutović was crowned Miss Serbia 2024 in a prestigious event at Belgrade's Sava Center, where her poise, confidence, and dedication to humanitarian work distinguished her as Serbia's representative for Miss World 2024.",
      byline: "By Camilla Saurez · 20 June 2024",
      image: "/images/miss-world/news/news-serbia.jpg",
    },
    {
      kicker: "News",
      title: "Miss World Krystyna Pyszková Lands in Vietnam for Miss World press conference",
      dek: "Miss World Krystyna Pyszkova's arrival in Vietnam marks the beginning of an exciting journey towards the prestigious Miss World event, as she sets the stage for an unforgettable press conference.",
      byline: "By Aakanksha Chugh · 19 June 2024",
      image: "/images/miss-world/news/news-vietnam.jpg",
    },
    {
      kicker: "News",
      title: "Julia Aguilar Crowned Miss World Nicaragua 2024",
      dek: "Julia Aguilar was crowned Miss World Nicaragua 2024 in Managua, impressing with her beauty, intelligence, and advocacy for women's education, and will represent Nicaragua at the Miss World 2024 pageant.",
      byline: "By Camilla Saurez · 03 June 2024",
      image: "/images/miss-world/news/news-nicaragua.jpg",
    },
    ],
  },
  {
    id: "hall",
    label: "Miss World : Hall Of Fame",
    dek: "Titleholders of Miss World, 2010 to 2019.",
    layout: "roll",
    body: [],
    pieces: [
    {
      kicker: "2019",
      title: "Toni-Ann Singh",
      dek: "Jamaica · 23 years · 167 cm",
      byline: "Jamaica · 23 years · 167 cm",
      image: "/images/miss-world/titleholder-2019.jpg",
      reactions: { like: 151, dislike: 640, love: 57, flower: 25 },
    },
    {
      kicker: "2018",
      title: "Vanessa Ponce de León",
      dek: "Mexico · 26 years · 170 cm",
      byline: "Mexico · 26 years · 170 cm",
      image: "/images/miss-world/titleholder-2018.jpg",
      reactions: { like: 2327, dislike: 6504, love: 118, flower: 77 },
    },
    {
      kicker: "2017",
      title: "Manushi Chhillar",
      dek: "India · 20 years · 175 cm",
      byline: "India · 20 years · 175 cm",
      image: "/images/miss-world/titleholder-2017.jpg",
      reactions: { like: 3160, dislike: 1195, love: 4741, flower: 569 },
    },
    {
      kicker: "2016",
      title: "Stephanie Del Valle Díaz",
      dek: "Puerto Rico · 20 years · 176 cm",
      byline: "Puerto Rico · 20 years · 176 cm",
      image: "/images/miss-world/titleholder-2016.jpg",
      reactions: { like: 1013, dislike: 14153, love: 14, flower: 9 },
    },
    {
      kicker: "2015",
      title: "Mireia Lalaguna",
      dek: "Spain · 23 years · 177 cm",
      byline: "Spain · 23 years · 177 cm",
      image: "/images/miss-world/titleholder-2015.jpg",
      reactions: { like: 1426, dislike: 9380, love: 149, flower: 59 },
    },
    {
      kicker: "2014",
      title: "Rolene Strauss",
      dek: "South Africa · 22 years · 177 cm",
      byline: "South Africa · 22 years · 177 cm",
      image: "/images/miss-world/titleholder-2014.jpg",
      reactions: { like: 246, dislike: 10330, love: 90, flower: 59 },
    },
    {
      kicker: "2013",
      title: "Megan Young",
      dek: "Philippines · 23 years · 170 cm",
      byline: "Philippines · 23 years · 170 cm",
      image: "/images/miss-world/titleholder-2013.jpg",
      reactions: { like: 2123, dislike: 8724, love: 1380, flower: 952 },
    },
    {
      kicker: "2012",
      title: "Yu Wenxia",
      dek: "China · 23 years · 178 cm",
      byline: "China · 23 years · 178 cm",
      image: "/images/miss-world/titleholder-2012.jpg",
      reactions: { like: 11, dislike: 70, love: 3, flower: 2 },
    },
    {
      kicker: "2011",
      title: "Ivian Sarcos",
      dek: "Venezuela · 22 years · 180 cm",
      byline: "Venezuela · 22 years · 180 cm",
      image: "/images/miss-world/titleholder-2011.jpg",
      reactions: { like: 5, dislike: 116, love: 3, flower: 3 },
    },
    {
      kicker: "2010",
      title: "Alexandria Mills",
      dek: "United States of America · 18 years · 178 cm",
      byline: "United States of America · 18 years · 178 cm",
      image: "/images/miss-world/titleholder-2010.jpg",
      reactions: { like: 91, dislike: 28, love: 1, flower: 1 },
    },
    ],
  },
  {
    id: "2021-info",
    label: "Miss World 2021 : Info",
    dek: "The 70th edition, San Juan, 16 December 2021.",
    body: [
      "Miss World 2021 was originally scheduled to be held at the end of 2020 but was postponed due to the pandemic. On 8th March 2021, Miss World Puerto Rico organization confirmed that the 70th edition of Miss World will take place in San Juan, Puerto Rico on the abovementioned date.",
      "As of 26th October 2021, 89 contestants have been confirmed to compete at Miss World 2021 –"
],
    pieces: [
    {
      kicker: "Info",
      title: "Miss World 2021",
      dek: "Miss World 2021, the 70th edition of the Miss World pageant, is all set to be held on 16th December 2021 at the José Miguel Agrelot Coliseum in San Juan, Puerto Rico. Miss World 2019 Toni-Ann Singh of Jamaica will crown her successor at the end of the event finale. There was no pageant held in 2020 due to the rampant spread of Covid-19 across the world.",
      byline: "16 December 2021 · San Juan, Puerto Rico",
    },
    {
      kicker: "Delegate",
      title: "Joanna Kiose",
      dek: "Albania",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Ruth Carlos",
      dek: "Angola",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Amira Hidalgo",
      dek: "Argentina",
      byline: "Miss World 2021",
      image: "/images/miss-world/amira-hidalgo.jpg",
    },
    {
      kicker: "Delegate",
      title: "Mirna Bzdigian",
      dek: "Armenia",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Daria Goncharevich",
      dek: "Belarus",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Céline Van Ouytsel",
      dek: "Belgium",
      byline: "Miss World 2021",
      image: "/images/miss-world/celine-van-ouytsel.jpg",
    },
    {
      kicker: "Delegate",
      title: "Markeisha Young",
      dek: "Belize",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Alondra Mercado",
      dek: "Bolivia",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Adna Biber",
      dek: "Bosnia and Herzegovina",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Caroline Teixeira",
      dek: "Brazil",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Kathlyn Archibald-Drew",
      dek: "British Virgin Islands",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Phum Sophorn",
      dek: "Cambodia",
      byline: "Miss World 2021",
      image: "/images/miss-world/phum-sophorn.jpg",
    },
    {
      kicker: "Delegate",
      title: "Audrey Monkam",
      dek: "Cameroon",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Svetlana Mamaeva",
      dek: "Canada",
      byline: "Miss World 2021",
      image: "/images/miss-world/svetlana-mamaeva.jpg",
    },
    {
      kicker: "Delegate",
      title: "Rashana Hydes",
      dek: "Cayman Islands",
      byline: "Miss World 2021",
      image: "/images/miss-world/rashana-hydes.jpg",
    },
    {
      kicker: "Delegate",
      title: "Carol Drpic",
      dek: "Chile",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Andrea Aguilera",
      dek: "Colombia",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Tamara Dal Maso",
      dek: "Costa Rica",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Karolína Kopíncová",
      dek: "Czech Republic",
      byline: "Miss World 2021",
      image: "/images/miss-world/karolina-kopincova.jpg",
    },
    {
      kicker: "Delegate",
      title: "Emmy Pena",
      dek: "Dominican Republic",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Ámar Pacheco",
      dek: "Ecuador",
      byline: "Miss World 2021",
      image: "/images/miss-world/amar-pacheco.jpg",
    },
    {
      kicker: "Delegate",
      title: "Rehema Muthamia",
      dek: "England",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Lucila Benita",
      dek: "Equatorial Guinea",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Rediet Berhanu",
      dek: "Ethiopia",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Emilia Lepomäki",
      dek: "Finland",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "April Benayoum",
      dek: "France",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Monique Mawulawe",
      dek: "Ghana",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Janice Sampere",
      dek: "Gibraltar",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Prescilla Larose",
      dek: "Guadeloupe",
      byline: "Miss World 2021",
      image: "/images/miss-world/prescilla-larose.jpg",
    },
    {
      kicker: "Delegate",
      title: "Michelle Calderón",
      dek: "Guatemala",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Nene Bah",
      dek: "Guinea",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Itchacénia Da Costa",
      dek: "Guinea-Bissau",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Erlande Berger",
      dek: "Haiti",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Dayana Bordas",
      dek: "Honduras",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Manasa Varanasi",
      dek: "India",
      byline: "Miss World 2021",
      image: "/images/miss-world/manasa-varanasi.jpg",
    },
    {
      kicker: "Delegate",
      title: "Carla Yules",
      dek: "Indonesia",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Pamela Uba",
      dek: "Ireland",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Claudia Motta",
      dek: "Italy",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Khalia Hall",
      dek: "Jamaica",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Tamaki Hoshi",
      dek: "Japan",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Sharon Obara",
      dek: "Kenya",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Tara Hong",
      dek: "South Korea",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Phonvilai Luanglath",
      dek: "Laos",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Tiisetso Seliane",
      dek: "Lesotho",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Emilie Boland",
      dek: "Luxembourg",
      byline: "Miss World 2021",
      image: "/images/miss-world/emilie-boland.jpg",
    },
    {
      kicker: "Delegate",
      title: "Nellie Anjaratiana",
      dek: "Madagascar",
      byline: "Miss World 2021",
      image: "/images/miss-world/nellie-anjaratiana.jpg",
    },
    {
      kicker: "Delegate",
      title: "Lavanya Sivaji",
      dek: "Malaysia",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Naomi Dingli",
      dek: "Malta",
      byline: "Miss World 2021",
      image: "/images/miss-world/naomi-dingli.jpg",
    },
    {
      kicker: "Delegate",
      title: "Angélique Sanson",
      dek: "Mauritius",
      byline: "Miss World 2021",
      image: "/images/miss-world/angelique-sanson.jpg",
    },
    {
      kicker: "Delegate",
      title: "Karolina Vidales",
      dek: "Mexico",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Natalija Labovic",
      dek: "Montenegro",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Annerie Mare",
      dek: "Namibia",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Namrata Shrestha",
      dek: "Nepal",
      byline: "Miss World 2021",
      image: "/images/miss-world/namrata-shrestha.jpg",
    },
    {
      kicker: "Delegate",
      title: "Lizzy Dobbe",
      dek: "Netherlands",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Sheynnis Palacios",
      dek: "Nicaragua",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Oluchi Madubuike",
      dek: "Nigeria",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Anna Leitch",
      dek: "Northern Ireland",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Krysthelle Barretto",
      dek: "Panama",
      byline: "Miss World 2021",
      image: "/images/miss-world/krysthelle-barretto.jpg",
    },
    {
      kicker: "Delegate",
      title: "Bethania Borba",
      dek: "Paraguay",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Paula Montes",
      dek: "Peru",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Tracy Perez",
      dek: "Philippines",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Karolina Bielawska",
      dek: "Poland",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Lidy Alves",
      dek: "Portugal",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Aryam Díaz",
      dek: "Puerto Rico",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Naomie Nishimwe",
      dek: "Rwanda",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Claudia Todd",
      dek: "Scotland",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Andrijana Savic",
      dek: "Serbia",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Kelly-Marry Anette",
      dek: "Seychelles",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Penda Sy",
      dek: "Senegal",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Khai Ling Ho",
      dek: "Singapore",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Leona Novoberdaliu",
      dek: "Slovakia",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Maja Colic",
      dek: "Slovenia",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Shudufhadzo Musida",
      dek: "South Africa",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Bakhita Nhial",
      dek: "South Sudan",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Tyler Theophane",
      dek: "Saint Lucia",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Ana García",
      dek: "Spain",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Gabriella Lomm Mann",
      dek: "Sweden",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Julianna Rugumisa",
      dek: "Tanzania",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Jeanine Brandt",
      dek: "Trinidad and Tobago",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Amani Layouni",
      dek: "Tunisia",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Dílara Korkmaz",
      dek: "Turkey",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Elizabeth Bagaya",
      dek: "Uganda",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Aleksandra Yaremchuk",
      dek: "Ukraine",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Shree Saini",
      dek: "United States of America",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Valentina Camejo",
      dek: "Uruguay",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Alejandra Conde",
      dek: "Venezuela",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Ðo Thi Hà",
      dek: "Vietnam",
      byline: "Miss World 2021",
    },
    {
      kicker: "Delegate",
      title: "Olivia Harris",
      dek: "Wales",
      byline: "Miss World 2021",
    },
    ],
  },
  {
    id: "2021-news",
    label: "Miss World 2021 : News",
    dek: "The 70th edition, from the desk.",
    body: [],
    pieces: [
    {
      kicker: "News",
      title: "All about Miss Universe Nicaragua 2023 Sheynnis Palacios Cornejo",
      dek: "Here’s everything you need to know about Miss Universe Nicaragua 2023 Sheynnis Palacios, preparing to represent her country at Miss Universe 2023.",
      byline: "By Priya Bhardwaj · 07 August 2023",
    },
    {
      kicker: "News",
      title: "Karolin Kippasto is Miss International Estonia 2023",
      dek: "Estonia is set to return to Miss International after almost a decade as Karolin Kippasto has been designated as Miss International Estonia 2023 who will now represent her country at Miss International 2023.",
      byline: "By Priya Bhardwaj · 27 July 2023",
    },
    {
      kicker: "News",
      title: "Miss World 2022 Karolina Bielawska celebrates one year crowning anniversary",
      dek: "Karolina Bielawska was crowned Miss World 2021/22 at the finale held at the Coca-Cola Music Hall in San Juan, Puerto Rico on 16th March 2022. A year later, Karolina is celebrating her one-year anniversary as she prepares to crown her successor in a few months in UAE.",
      byline: "By Priya Bhardwaj · 16 March 2023",
    },
    {
      kicker: "News",
      title: "Miss Universe calling for Sheynnis Palacios Cornejo?",
      dek: "In a series of Q/A on social media, Sheynnis Palacaios hinted at participating in Miss Nicaragua sometime in the future. Miss Nicaragua is the official preliminary to represent Nicaragua at Miss Universe.",
      byline: "By Priya Bhardwaj · 25 January 2023",
    },
    {
      kicker: "News",
      title: "Emmy Peña – From Miss World to Miss Universe?",
      dek: "Miss Universe Dominican Republic 2023 Wishlist - Emmy Peña.",
      byline: "By Priya Bhardwaj · 21 January 2023",
    },
    {
      kicker: "News",
      title: "Andrea Aguilera appointed Miss Earth Colombia 2022",
      dek: "Andrea Aguilera is the newly appointed Miss Earth Colombia 2022 and will represent Colombia at Miss Earth 2022.",
      byline: "By Priya Bhardwaj · 12 September 2022",
    },
    {
      kicker: "News",
      title: "Miss World 2021 Karolina Bielawska wins academic award",
      dek: "Miss World 2021 Karolina Bielawska has recently won first place in a competition for the best Bachelor Degree thesis organized by the Polish Economic Society.",
      byline: "By Angelique Reyes · 21 June 2022",
    },
    {
      kicker: "News",
      title: "Miss World 2021 Karolina Bielawska and Miss Grand International 2021 Nguyen Thuc Thuy Tien to attend Miss World Malaysia 2022",
      dek: "The reigning queens, Miss World 2021 Karolina Bielawska and Miss Grand International 2021 Nguyen Thuc Thuy Tien, will be attending Miss World Malaysia 2022.",
      byline: "By Angelique Reyes · 16 June 2022",
    },
    {
      kicker: "News",
      title: "Miss World Africa 2021 Olivia Yacé appointed Ambassador of Tourism of Côte d’Ivoire",
      dek: "The stunning Miss World Africa 2021 Olivia Yacé has been appointed as the Ambassador of Tourism of Côte d’Ivoire by the Ministry of Tourism and Leisure.",
      byline: "By Camilla Suarez · 03 June 2022",
    },
    {
      kicker: "News",
      title: "Miss World Africa 2021 Olivia Yace made Honorary Citizen of the commune of Cocody",
      dek: "Miss World Africa 2021 Olivia Yace of Cote D’Ivoire was recently appreciated for her performance and was made honorary citizen of the commune of Cocody.",
      byline: "By Angelique Reyes · 07 May 2022",
    },
    {
      kicker: "News",
      title: "Homecoming of Miss World 2022 Karolina Bielawska",
      dek: "After a wait of 33 years, Miss World crown finally tasted Polish air as Miss World 2022 Karolina Bielawska reached her home country on Monday. The queen arrived clad in her blue crown and white pant-suit just a few hours ago while polish paparazzi and her devoted fans flocked the gates of Warsaw Cho ....",
      byline: "By Angelique Reyes · 28 March 2022",
    },
    {
      kicker: "News",
      title: "Olivia Yace creates history for Cote D’Ivoire at Miss World 2021",
      dek: "Miss World Cote D’Ivoire 2021 Olivia Yace has achieved a historic placement for the country after being adjudged as second runner-up at Miss World 2021.",
      byline: "By Angelique Reyes · 22 March 2022",
    },
    {
      kicker: "News",
      title: "Karolina Bielawska of Poland crowned Miss World 2021",
      dek: "The results of Miss World 2021 are: Winner - Karolina Bielawska of Poland, First runner-up – Shree Saini of USA and Second runner-up – Olivia Yace of Cote D’Ivoire.",
      byline: "By Angelique Reyes · 17 March 2022",
      image: "/images/miss-world/karolina-bielawska.jpg",
    },
    {
      kicker: "News",
      title: "Miss World 2021 Top 6 Q/A round",
      dek: "The Top 6 finalists for Miss World 2021 included Miss World USA 2021 Shree Saini, Miss World Cote D'Ivoire 2021 Olivia Yacé, Miss World Poland 2021 Karolina Bielawska, Miss World Indonesia 2021 Carla Yules, Miss World Mexico 2021 Karolina Vidales and Miss World Northern Ireland 2021 Anna Leitch. Her ....",
      byline: "By Camilla Suarez · 17 March 2022",
    },
    {
      kicker: "News",
      title: "Miss World 2021 Live Blog Full Results",
      dek: "Miss World 2021 finale to be held on 16th December 2021 at the José Miguel Agrelot Coliseum in San Juan, Puerto Rico. Toni-Ann Singh of Jamaica will crown her successor at the end of the event finale.",
      byline: "By Priya Bhardwaj · 16 March 2022",
    },
    {
      kicker: "News",
      title: "Latina Powerhouses of Miss World 2021",
      dek: "The Latina Powerhouses emerging as strong contenders for Miss World 2021 are Andrea Aguilera of Colombia, Alejandra Conde of Venezuela, Karolina Vidales of Mexico, Sheynnis Palacios of Nicaragua, Carol Drpic of Chile and Aryam Díaz of Puerto Rico.",
      byline: "By Angelique Reyes · 15 March 2022",
    },
    {
      kicker: "News",
      title: "Miss World 2021 Top 15 Final Hot Picks",
      dek: "Miss World 2021 Top 15 final hot picks are Sienna Evans representing Bahamas, Caroline Teixeira representing Brazil, Carol Drpic representing Chile, Andrea Aguilera representing Colombia, Olivia Yacé representing Cote D'Ivoire, Emmy Peña representing Dominican Republic, Ámar Pacheco representing Ecu ....",
      byline: "By Priya Bhardwaj · 15 March 2022",
    },
    {
      kicker: "News",
      title: "Miss World 2021: Reboot",
      dek: "Here’s everything you need to know so far on Miss World 2021 as the delegates have arrived back in Puerto Rico for the grand finale.",
      byline: "By Camilla Suarez · 14 March 2022",
    },
    {
      kicker: "News",
      title: "Miss World 2021 Meet the Top 40 Semi-finalists",
      dek: "Miss World 2021 Top 40 Semi-finalists are Amira Hidalgo representing Argentina, Sienna Evans representing Bahamas, Palesa Mofele representing Botswana, Caroline Teixeira representing Brazil, Audrey Monkam representing Cameroon, Svetlana Mamaeva representing Canada, Carol Drpic representing Chile, Ji ....",
      byline: "By Priya Bhardwaj · 11 March 2022",
    },
    {
      kicker: "News",
      title: "Former Miss World Stephanie Del Valle withdraws participation from Miss World 2021 finale",
      dek: "Miss World 2016 Stephanie Del Valle has withdrawn her participation from Miss World 2021 finals after being sued for embezzlement.",
      byline: "By Priya Bhardwaj · 02 March 2022",
    },
    ],
  },
  {
    id: "contestants",
    label: "Miss World 2021 : Contestants",
    dek: "Delegates confirmed for Miss World 2021.",
    layout: "portraits",
    body: [],
    pieces: [
    {
      kicker: "Contestant",
      title: "Amira Hidalgo",
      dek: "Argentina · 23 Years",
      byline: "Argentina · 23 Years",
      image: "/images/miss-world/amira-hidalgo.jpg",
      reactions: { like: 160, dislike: 22, love: 220, flower: 51 },
    },
    {
      kicker: "Contestant",
      title: "Céline Van Ouytsel",
      dek: "Belgium · 25 Years",
      byline: "Belgium · 25 Years",
      image: "/images/miss-world/celine-van-ouytsel.jpg",
      reactions: { like: 131, dislike: 1821, love: 18, flower: 8 },
    },
    {
      kicker: "Contestant",
      title: "Alondra Mercado Campos",
      dek: "Bolivia · 19 Years",
      byline: "Bolivia · 19 Years",
      image: "/images/miss-world/alondra-mercado-campos.jpg",
      reactions: { like: 81, dislike: 15, love: 90, flower: 30 },
    },
    {
      kicker: "Contestant",
      title: "Phum Sophorn",
      dek: "Cambodia · 18 Years",
      byline: "Cambodia · 18 Years",
      image: "/images/miss-world/phum-sophorn.jpg",
      reactions: { like: 128, dislike: 18, love: 160, flower: 100 },
    },
    {
      kicker: "Contestant",
      title: "Svetlana Mamaeva",
      dek: "Canada · 21 Years",
      byline: "Canada · 21 Years",
      image: "/images/miss-world/svetlana-mamaeva.jpg",
      reactions: { like: 117, dislike: 30, love: 4319, flower: 4460 },
    },
    {
      kicker: "Contestant",
      title: "Rashana Hydes",
      dek: "Cayman Islands · 24 Years",
      byline: "Cayman Islands · 24 Years",
      image: "/images/miss-world/rashana-hydes.jpg",
      reactions: { like: 79, dislike: 21, love: 150, flower: 110 },
    },
    {
      kicker: "Contestant",
      title: "Andrea Montero Briceño",
      dek: "Costa Rica · 21 Years",
      byline: "Costa Rica · 21 Years",
      image: "/images/miss-world/andrea-montero.jpg",
      reactions: { like: 90, dislike: 10, love: 100, flower: 40 },
    },
    {
      kicker: "Contestant",
      title: "Karolína Kopíncová",
      dek: "Czech Republic · 22 Years",
      byline: "Czech Republic · 22 Years",
      image: "/images/miss-world/karolina-kopincova.jpg",
      reactions: { like: 1201, dislike: 18, love: 4740, flower: 4600 },
    },
    {
      kicker: "Contestant",
      title: "Ámar Pacheco Ibarra",
      dek: "Ecuador · 24 Years",
      byline: "Ecuador · 24 Years",
      image: "/images/miss-world/amar-pacheco.jpg",
      reactions: { like: 70, dislike: 12, love: 120, flower: 80 },
    },
    {
      kicker: "Contestant",
      title: "Monique Mawulawe Agbedekpui",
      dek: "Ghana · 20 Years",
      byline: "Ghana · 20 Years",
      image: "/images/miss-world/monique-agbedekpui.jpg",
      reactions: { like: 183, dislike: 60, love: 140, flower: 60 },
    },
    {
      kicker: "Contestant",
      title: "Prescilla Larose",
      dek: "Guadeloupe · 25 Years",
      byline: "Guadeloupe · 25 Years",
      image: "/images/miss-world/prescilla-larose.jpg",
      reactions: { like: 90, dislike: 7, love: 100, flower: 60 },
    },
    {
      kicker: "Contestant",
      title: "Hillary Mendoza",
      dek: "Guatemala · 22 Years",
      byline: "Guatemala · 22 Years",
      image: "/images/miss-world/hillary-mendoza.jpg",
      reactions: { like: 63, dislike: 10, love: 48, flower: 35 },
    },
    {
      kicker: "Contestant",
      title: "Manasa Varanasi",
      dek: "India · 24 Years",
      byline: "India · 24 Years",
      image: "/images/miss-world/manasa-varanasi.jpg",
      reactions: { like: 103, dislike: 12, love: 260, flower: 230 },
    },
    {
      kicker: "Contestant",
      title: "Pricilia Carla Yules",
      dek: "Indonesia · 24 Years",
      byline: "Indonesia · 24 Years",
      image: "/images/miss-world/pricilia-yules.jpg",
      reactions: { like: 2641, dislike: 14, love: 5091, flower: 4930 },
    },
    {
      kicker: "Contestant",
      title: "Maria Kaneya",
      dek: "Japan · 18 Years",
      byline: "Japan · 18 Years",
      image: "/images/miss-world/maria-kaneya.jpg",
      reactions: { like: 51, dislike: 11, love: 40, flower: 30 },
    },
    {
      kicker: "Contestant",
      title: "Phonevilai Luanglath",
      dek: "Laos · 24 Years",
      byline: "Laos · 24 Years",
      image: "/images/miss-world/phonevilai-luanglath.jpg",
      reactions: { like: 62, dislike: 9, love: 31, flower: 30 },
    },
    {
      kicker: "Contestant",
      title: "Emilie Boland",
      dek: "Luxembourg · 25 Years",
      byline: "Luxembourg · 25 Years",
      image: "/images/miss-world/emilie-boland.jpg",
      reactions: { like: 37, dislike: 23, love: 3322, flower: 370 },
    },
    {
      kicker: "Contestant",
      title: "Nellie Anjaratiana",
      dek: "Madagascar · 24 Years",
      byline: "Madagascar · 24 Years",
      image: "/images/miss-world/nellie-anjaratiana.jpg",
      reactions: { like: 651, dislike: 13, love: 30, flower: 20 },
    },
    {
      kicker: "Contestant",
      title: "Naomi Dingli",
      dek: "Malta · 26 Years",
      byline: "Malta · 26 Years",
      image: "/images/miss-world/naomi-dingli.jpg",
      reactions: { like: 74, dislike: 40, love: 101, flower: 42 },
    },
    {
      kicker: "Contestant",
      title: "Angélique Sanson",
      dek: "Mauritius · 25 Years",
      byline: "Mauritius · 25 Years",
      image: "/images/miss-world/angelique-sanson.jpg",
      reactions: { like: 138, dislike: 45, love: 280, flower: 40 },
    },
    {
      kicker: "Contestant",
      title: "Natalia Labović",
      dek: "Montenegro · 28 Years",
      byline: "Montenegro · 28 Years",
      image: "/images/miss-world/natalia-labovic.jpg",
      reactions: { like: 122, dislike: 29, love: 141, flower: 60 },
    },
    {
      kicker: "Contestant",
      title: "Namrata Shrestha",
      dek: "Nepal · 23 Years",
      byline: "Nepal · 23 Years",
      image: "/images/miss-world/namrata-shrestha.jpg",
      reactions: { like: 143, dislike: 32, love: 381, flower: 41 },
    },
    {
      kicker: "Contestant",
      title: "Sheynnis Palacios Cornejo",
      dek: "Nicaragua · 21 Years",
      byline: "Nicaragua · 21 Years",
      image: "/images/miss-world/sheynnis-palacios.jpg",
      reactions: { like: 83, dislike: 10, love: 50, flower: 40 },
    },
    {
      kicker: "Contestant",
      title: "Krysthelle Barretto",
      dek: "Panama · 26 Years",
      byline: "Panama · 26 Years",
      image: "/images/miss-world/krysthelle-barretto.jpg",
      reactions: { like: 71, dislike: 21, love: 51, flower: 40 },
    },
    ],
  },
  {
    id: "winners",
    label: "Miss World 2021 : Winners",
    dek: "16 March 2022 · Coca-Cola Music Hall, San Juan.",
    layout: "results",
    body: [
      "The 70th Miss World was held on 16 March 2022 at the Coca-Cola Music Hall in San Juan, Puerto Rico. Toni-Ann Singh of Jamaica crowned her successor. Ninety-seven delegates competed, and forty reached the final night.",
      "The coronation had been scheduled for 16 December 2021 at the José Miguel Agrelot Coliseum. It was moved after a COVID-19 outbreak in Puerto Rico. There was no Miss World in 2020.",
    ],
    pieces: [
    {
      kicker: "Winner",
      title: "Karolina Bielawska",
      dek: "Poland",
      byline: "Karolina Bielawska, 22, was crowned Miss World. She stands 179 cm and studies management at the Technical University of Łódź. She is the second Miss World from Poland, after Aneta Kręglicka in 1989.",
      image: "/images/miss-world/karolina-bielawska.jpg",
    },
    {
      kicker: "1st Runner-up",
      title: "Shree Saini",
      dek: "United States",
      byline: "Shree Saini was also named Beauty With a Purpose.",
    },
    {
      kicker: "2nd Runner-up",
      title: "Olivia Yacé",
      dek: "Côte d'Ivoire",
      byline: "Olivia Yacé placed second and was crowned Miss World Africa.",
    },
    {
      kicker: "Continental Queen",
      title: "Olivia Yacé",
      dek: "Côte d'Ivoire",
      byline: "Africa",
    },
    {
      kicker: "Continental Queen",
      title: "Shree Saini",
      dek: "United States",
      byline: "Americas",
    },
    {
      kicker: "Continental Queen",
      title: "Pricilia Carla Yules",
      dek: "Indonesia",
      byline: "Asia",
      image: "/images/miss-world/pricilia-yules.jpg",
    },
    {
      kicker: "Continental Queen",
      title: "Emmy Peña",
      dek: "Dominican Republic",
      byline: "Caribbean",
    },
    {
      kicker: "Continental Queen",
      title: "Anna Leitch",
      dek: "Northern Ireland",
      byline: "Europe",
    },
    {
      kicker: "Top 6",
      title: "Shree Saini",
      dek: "United States",
      byline: "Top 6",
    },
    {
      kicker: "Top 6",
      title: "Karolina Bielawska",
      dek: "Poland",
      byline: "Top 6",
      image: "/images/miss-world/karolina-bielawska.jpg",
    },
    {
      kicker: "Top 6",
      title: "Pricilia Carla Yules",
      dek: "Indonesia",
      byline: "Top 6",
      image: "/images/miss-world/pricilia-yules.jpg",
    },
    {
      kicker: "Top 6",
      title: "Karolina Vidales",
      dek: "Mexico",
      byline: "Top 6",
    },
    {
      kicker: "Top 6",
      title: "Anna Leitch",
      dek: "Northern Ireland",
      byline: "Top 6",
    },
    {
      kicker: "Top 6",
      title: "Olivia Yacé",
      dek: "Côte d'Ivoire",
      byline: "Top 6",
    },
    {
      kicker: "Top 13",
      title: "Andrea Aguilera",
      dek: "Colombia",
      byline: "Top 13",
    },
    {
      kicker: "Top 13",
      title: "Karolína Kopíncová",
      dek: "Czech Republic",
      byline: "Top 13",
      image: "/images/miss-world/karolina-kopincova.jpg",
    },
    {
      kicker: "Top 13",
      title: "April Benayoum",
      dek: "France",
      byline: "Top 13",
    },
    {
      kicker: "Top 13",
      title: "Manasa Varanasi",
      dek: "India",
      byline: "Top 13",
      image: "/images/miss-world/manasa-varanasi.jpg",
    },
    {
      kicker: "Top 13",
      title: "Tracy Maureen Perez",
      dek: "Philippines",
      byline: "Top 13",
    },
    {
      kicker: "Top 13",
      title: "Khadija Omar",
      dek: "Somalia",
      byline: "Top 13",
    },
    {
      kicker: "Top 13",
      title: "Hà Đỗ",
      dek: "Vietnam",
      byline: "Digital Media Challenge",
    },
    ],
  },
  {
    id: "videos",
    label: "Miss World 2021 : Video Gallery",
    dek: "Head to Head Challenge, group by group.",
    layout: "videos",
    body: [],
    pieces: [
    {
      kicker: "Video",
      title: "Miss World 2021 Head to Head Challenge Group 1 Full Video",
      dek: "Head to Head Challenge, Miss World 2021.",
      byline: "Miss World 2021",
      image: "/images/miss-world/video-group-1.jpg",
      href: "https://www.youtube.com/watch?v=5wpBMCSe1ks",
    },
    {
      kicker: "Video",
      title: "Miss World 2021 Head to Head Challenge Group 2 Full Video",
      dek: "Head to Head Challenge, Miss World 2021.",
      byline: "Miss World 2021",
      image: "/images/miss-world/video-group-2.jpg",
      href: "https://www.youtube.com/watch?v=A3gKjF1KIok",
    },
    {
      kicker: "Video",
      title: "Miss World 2021 Head to Head Challenge Group 3 Full Video",
      dek: "Head to Head Challenge, Miss World 2021.",
      byline: "Miss World 2021",
      image: "/images/miss-world/video-group-3.jpg",
      href: "https://www.youtube.com/watch?v=W3xj436d7WA",
    },
    {
      kicker: "Video",
      title: "Miss World 2021 Head to Head Challenge Group 4 Full Video",
      dek: "Head to Head Challenge, Miss World 2021.",
      byline: "Miss World 2021",
      image: "/images/miss-world/video-group-4.jpg",
      href: "https://www.youtube.com/watch?v=sWxp9B8D06Q",
    },
    {
      kicker: "Video",
      title: "Miss World 2021 Head to Head Challenge Group 5 Full Video",
      dek: "Head to Head Challenge, Miss World 2021.",
      byline: "Miss World 2021",
      image: "/images/miss-world/video-group-5.jpg",
      href: "https://www.youtube.com/watch?v=f7qp8hogFUk",
    },
    {
      kicker: "Video",
      title: "Miss World 2021 Head to Head Challenge Group 6 Full Video",
      dek: "Head to Head Challenge, Miss World 2021.",
      byline: "Miss World 2021",
      image: "/images/miss-world/video-group-6.jpg",
      href: "https://www.youtube.com/watch?v=UwrdUKq04w4",
    },
    {
      kicker: "Video",
      title: "Miss World 2021 Head to Head Challenge Group 7 Full Video",
      dek: "Head to Head Challenge, Miss World 2021.",
      byline: "Miss World 2021",
      image: "/images/miss-world/video-group-7.jpg",
      href: "https://www.youtube.com/watch?v=chjSM_wiFeU",
    },
    {
      kicker: "Video",
      title: "Miss World 2021 Head to Head Challenge Group 8 Full Video",
      dek: "Head to Head Challenge, Miss World 2021.",
      byline: "Miss World 2021",
      image: "/images/miss-world/video-group-8.jpg",
      href: "https://www.youtube.com/watch?v=AAZJLeqy4Ww",
    },
    {
      kicker: "Video",
      title: "Miss World 2021 Head to Head Challenge Group 9 Full Video",
      dek: "Head to Head Challenge, Miss World 2021.",
      byline: "Miss World 2021",
      image: "/images/miss-world/video-group-9.jpg",
      href: "https://www.youtube.com/watch?v=fMJGYUg9tVM",
    },
    {
      kicker: "Video",
      title: "Miss World 2021 Head to Head Challenge Group 10 Full Video",
      dek: "Head to Head Challenge, Miss World 2021.",
      byline: "Miss World 2021",
      image: "/images/miss-world/video-group-10.jpg",
      href: "https://www.youtube.com/watch?v=dqzLPaFcaVU",
    },
    ],
  },
];

